import type { Metadata } from "next";
import { Amarante, Inter } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "sonner";
import "./globals.css";
import { CursorRouteReset } from "@/components/global/CursorUnmount";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const amarante = Amarante({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${amarante.variable} font-sans  antialiased flex flex-col min-h-svh`}>
        <CursorRouteReset />
        <NuqsAdapter>{children}</NuqsAdapter>
        <Toaster richColors />
      </body>
    </html>
  );
}
